name: Build Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew || true

      - name: Build
        run: |
          if [ -f gradlew ]; then
            ./gradlew build
          else
            gradle build
          fi

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: EconyxShop
          path: build/libs/*.jar
